title: Paulius' PCR method repo
description: This is where different PCR methods are collected and described!
theme: just-the-docs

url: https://just-the-docs.github.io
logo: "/assets/images/web.png"
aux_links:
  My CV: https://pauliusbaltrusis.github.io/markdown-cv/
nav:
  - Home: /
  - About:
      - About me: /aboutme
      - About this website: /abouthiswebsite
  - ddPCR:
      - DNA: /DNA
      - RNA: /RNA
      - Protein: /Protein
  - qPCR: /qPCR
