title: Paulius Baltrusis
description: This is where different PCR methods are collected and described!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  My CV: https://pauliusbaltrusis.github.io/
nav:
  - Home: /
  - About: 
      - About me: /aboutme
      - About this website: /abouthiswebsite
  - ddPCR:
      - DNA: /DNA
      - RNA: /RNA
      - Protein: /Protein
  - qPCR: /qPCR
